package com.example.accountkeeper.ui.theme

data class AppStrings(
    val home: String,
    val statistics: String,
    val settings: String,
    val totalAssets: String,
    val totalBalance: String,
    val thisMonth: String,
    val income: String,
    val expense: String,
    val recentTransactions: String,
    val addTransaction: String,
    val editTransaction: String,
    val deleteTransaction: String,
    val deleteConfirm: String,
    val amount: String,
    val date: String,
    val category: String,
    val note: String,
    val save: String,
    val daily: String,
    val weekly: String,
    val monthly: String,
    val yearly: String,
    val custom: String,
    val totalIncome: String,
    val totalExpense: String,
    val categoryRanking: String,
    val noTransactions: String,
    val selectRange: String,
    val manualDataManagement: String,
    val uploadBackup: String,
    val exportAll: String,
    val generalSettings: String,
    val darkMode: String,
    val language: String,
    val currencySymbol: String,
    val newCategory: String,
    val name: String,
    val nameEmptyError: String,
    val nameExistsError: String,
    val add: String,
    val cancel: String,
    val ok: String,
    val change: String,
    val other: String,
    val infoLimitation: String,
    val localBackupVault: String,
    val enableAutoBackup: String,
    val autoBackupDescription: String,
    val backupRetentionLimit: String,
    val backupRetentionDescription: String,
    val backupRetentionUnit: String,
    val backupThresholdDescription: String,
    val currentBackupStatus: String,
    val latestBackupFile: String,
    val noBackupFound: String,
    val createManualBackup: String,
    val manualBackupSuccess: String,
    val clearAllBackups: String,
    val backupsCleared: String,
    val openManualBackupVault: String,
    val categoryManagement: String,
    val categoryManagementDescription: String,
    val categoryAndTagManagement: String
)

val EnStrings = AppStrings(
    home = "Home",
    statistics = "Statistics",
    settings = "Settings",
    totalAssets = "Total Assets",
    totalBalance = "Total Balance",
    thisMonth = "This Month",
    income = "Income",
    expense = "Expense",
    recentTransactions = "Recent Transactions",
    addTransaction = "Add Transaction",
    editTransaction = "Edit Transaction",
    deleteTransaction = "Delete Transaction",
    deleteConfirm = "Are you sure you want to delete this transaction?",
    amount = "Amount",
    date = "Date",
    category = "Category",
    note = "Note",
    save = "Save",
    daily = "Daily",
    weekly = "Weekly",
    monthly = "Monthly",
    yearly = "Yearly",
    custom = "Custom",
    totalIncome = "Total Income",
    totalExpense = "Total Expense",
    categoryRanking = "Category Ranking",
    noTransactions = "No transactions found for this period.",
    selectRange = "Select Range",
    manualDataManagement = "Manual Data Management",
    uploadBackup = "Upload Standard Backup CSV",
    exportAll = "Export All Transactions to CSV",
    generalSettings = "General Settings",
    darkMode = "Dark Mode",
    language = "Language",
    currencySymbol = "Currency Symbol",
    newCategory = "New Category",
    name = "Name",
    nameEmptyError = "Name cannot be empty",
    nameExistsError = "Category already exists in this type",
    add = "Add",
    cancel = "Cancel",
    ok = "OK",
    change = "Change",
    other = "Other",
    infoLimitation = "Due to API limitations from WeChat and Alipay for personal developers, automatic syncing is disabled. Please upload a standard CSV file exported from this app to restore backups.",
    localBackupVault = "Local Auto Backup Vault",
    enableAutoBackup = "Enable Auto Backup",
    autoBackupDescription = "Automatically save to local sandbox on any add, delete, or modify operation",
    backupRetentionLimit = "Backup Retention Limit",
    backupRetentionDescription = "New backup retention limit",
    backupRetentionUnit = " copies",
    backupThresholdDescription = "Automatically delete oldest backups when threshold is exceeded",
    currentBackupStatus = "Current Backup Status",
    latestBackupFile = "Latest backup file: ",
    noBackupFound = "No available backup file found",
    createManualBackup = "Create Manual Backup Now",
    manualBackupSuccess = "Manual backup created successfully!",
    clearAllBackups = "Clear All Auto Backups",
    backupsCleared = "Auto backup pool has been forcibly cleared",
    openManualBackupVault = "Open Private Manual Backup Vault",
    categoryManagement = "Category Management",
    categoryManagementDescription = "Unified management of income and expense category information",
    categoryAndTagManagement = "Category & Tag Management"
)

val ZhStrings = AppStrings(
    home = "首页",
    statistics = "统计",
    settings = "设置",
    totalAssets = "总资产",
    totalBalance = "总余额",
    thisMonth = "本月",
    income = "收入",
    expense = "支出",
    recentTransactions = "近期交易",
    addTransaction = "记录交易",
    editTransaction = "修改交易",
    deleteTransaction = "删除交易",
    deleteConfirm = "确定要删除这条交易吗？",
    amount = "金额",
    date = "日期",
    category = "分类",
    note = "备注",
    save = "保存",
    daily = "日",
    weekly = "周",
    monthly = "月",
    yearly = "年",
    custom = "自定义",
    totalIncome = "总收入",
    totalExpense = "总支出",
    categoryRanking = "分类开销排行",
    noTransactions = "该时段内没有交易记录。",
    selectRange = "选择区间",
    manualDataManagement = "本地数据归档",
    uploadBackup = "导入标准 CSV 备份",
    exportAll = "导出全量账本至 CSV",
    generalSettings = "个性化设置",
    darkMode = "深色模式",
    language = "界面语言",
    currencySymbol = "货币符号",
    newCategory = "自定义分类",
    name = "分类名称",
    nameEmptyError = "分类名不能为空",
    nameExistsError = "该分类已经存在",
    add = "添加",
    cancel = "取消",
    ok = "确定",
    change = "修改",
    other = "其他",
    infoLimitation = "因受限于微信与支付宝开放平台对个人开发者的 API 限制，在线直连拉取功能暂不可用。请上传由本软件导出的标准 CSV 历史文件来完成数据合并覆盖。",
    localBackupVault = "本地自动备份安全柜",
    enableAutoBackup = "开启本地自动备份",
    autoBackupDescription = "任何增删改时自动向本地沙盒存入留档",
    backupRetentionLimit = "新备份生成保留上限",
    backupRetentionDescription = "新备份生成保留上限",
    backupRetentionUnit = " 份",
    backupThresholdDescription = "超过此设定阈值时，自动销毁最远历史备份",
    currentBackupStatus = "当前存档状态",
    latestBackupFile = "最新备份文件: ",
    noBackupFound = "尚未发现可用备份文件",
    createManualBackup = "立即生成手动备份",
    manualBackupSuccess = "手动内部备份已成功生成！",
    clearAllBackups = "清空所有自动存档",
    backupsCleared = "自动备份池已被强制清空",
    openManualBackupVault = "打开私有手工备份管理柜",
    categoryManagement = "分类配置",
    categoryManagementDescription = "统一管理收入与支出的分类信息",
    categoryAndTagManagement = "类别与标签管理"
)

val LocalAppStrings = androidx.compose.runtime.compositionLocalOf { EnStrings }
