package com.example.accountkeeper.ui.theme

data class AppStrings(
    val home: String,
    val statistics: String,
    val settings: String,
    val totalAssets: String,
    val income: String,
    val expense: String,
    val recentTransactions: String,
    val addTransaction: String,
    val editTransaction: String,
    val amount: String,
    val date: String,
    val category: String,
    val note: String,
    val save: String,
    val daily: String,
    val weekly: String,
    val monthly: String,
    val yearly: String,
    val custom: String,
    val totalIncome: String,
    val totalExpense: String,
    val categoryRanking: String,
    val noTransactions: String,
    val selectRange: String,
    val manualDataManagement: String,
    val uploadBackup: String,
    val exportAll: String,
    val generalSettings: String,
    val darkMode: String,
    val language: String,
    val currencySymbol: String,
    val newCategory: String,
    val name: String,
    val nameEmptyError: String,
    val nameExistsError: String,
    val add: String,
    val cancel: String,
    val ok: String,
    val change: String,
    val other: String,
    val infoLimitation: String
)

val EnStrings = AppStrings(
    home = "Home",
    statistics = "Statistics",
    settings = "Settings",
    totalAssets = "Total Assets",
    income = "Income",
    expense = "Expense",
    recentTransactions = "Recent Transactions",
    addTransaction = "Add Transaction",
    editTransaction = "Edit Transaction",
    amount = "Amount",
    date = "Date",
    category = "Category",
    note = "Note",
    save = "Save",
    daily = "Daily",
    weekly = "Weekly",
    monthly = "Monthly",
    yearly = "Yearly",
    custom = "Custom",
    totalIncome = "Total Income",
    totalExpense = "Total Expense",
    categoryRanking = "Category Ranking",
    noTransactions = "No transactions found for this period.",
    selectRange = "Select Range",
    manualDataManagement = "Manual Data Management",
    uploadBackup = "Upload Standard Backup CSV",
    exportAll = "Export All Transactions to CSV",
    generalSettings = "General Settings",
    darkMode = "Dark Mode",
    language = "Language",
    currencySymbol = "Currency Symbol",
    newCategory = "New Category",
    name = "Name",
    nameEmptyError = "Name cannot be empty",
    nameExistsError = "Category already exists in this type",
    add = "Add",
    cancel = "Cancel",
    ok = "OK",
    change = "Change",
    other = "Other",
    infoLimitation = "Due to API limitations from WeChat and Alipay for personal developers, automatic syncing is disabled. Please upload a standard CSV file exported from this app to restore backups."
)

val ZhStrings = AppStrings(
    home = "首页",
    statistics = "统计",
    settings = "设置",
    totalAssets = "总资产",
    income = "收入",
    expense = "支出",
    recentTransactions = "近期交易",
    addTransaction = "记录交易",
    editTransaction = "修改交易",
    amount = "金额",
    date = "日期",
    category = "分类",
    note = "备注",
    save = "保存",
    daily = "日",
    weekly = "周",
    monthly = "月",
    yearly = "年",
    custom = "自定义",
    totalIncome = "总收入",
    totalExpense = "总支出",
    categoryRanking = "分类开销排行",
    noTransactions = "该时段内没有交易记录。",
    selectRange = "选择区间",
    manualDataManagement = "本地数据归档",
    uploadBackup = "导入标准 CSV 备份",
    exportAll = "导出全量账本至 CSV",
    generalSettings = "个性化设置",
    darkMode = "深色模式",
    language = "界面语言",
    currencySymbol = "货币符号",
    newCategory = "自定义分类",
    name = "分类名称",
    nameEmptyError = "分类名不能为空",
    nameExistsError = "该分类已经存在",
    add = "添加",
    cancel = "取消",
    ok = "确定",
    change = "修改",
    other = "其他",
    infoLimitation = "因受限于微信与支付宝开放平台对个人开发者的 API 限制，在线直连拉取功能暂不可用。请上传由本软件导出的标准 CSV 历史文件来完成数据合并覆盖。"
)

val LocalAppStrings = androidx.compose.runtime.compositionLocalOf { EnStrings }
