package com.example.accountkeeper.ui.theme

data class AppStrings(
    val home: String,
    val statistics: String,
    val categoryStatistics: String,
    val settings: String,
    val dataManagement: String,
    val quickSettings: String,
    val customizeExperience: String,
    val dataManagementDescription: String,
    val generalSettings: String,
    val generalSettingsDescription: String,
    val about: String,
    val aboutDescription: String,
    val totalAssets: String,
    val totalBalance: String,
    val thisMonth: String,
    val income: String,
    val expense: String,
    val balanceOverall: String,
    val startDate: String,
    val endDate: String,
    val recentTransactions: String,
    val addTransaction: String,
    val editTransaction: String,
    val deleteTransaction: String,
    val deleteConfirm: String,
    val amount: String,
    val date: String,
    val category: String,
    val note: String,
    val save: String,
    val daily: String,
    val weekly: String,
    val monthly: String,
    val yearly: String,
    val custom: String,
    val totalIncome: String,
    val totalExpense: String,
    val categoryRanking: String,
    val noTransactions: String,
    val selectRange: String,
    val manualDataManagement: String,
    val uploadBackup: String,
    val exportAll: String,
    val darkMode: String,
    val language: String,
    val currencySymbol: String,
    val newCategory: String,
    val name: String,
    val nameEmptyError: String,
    val nameExistsError: String,
    val add: String,
    val cancel: String,
    val ok: String,
    val change: String,
    val other: String,
    val infoLimitation: String,
    val localBackupVault: String,
    val enableAutoBackup: String,
    val autoBackupDescription: String,
    val backupRetentionLimit: String,
    val backupRetentionDescription: String,
    val backupRetentionUnit: String,
    val backupThresholdDescription: String,
    val currentBackupStatus: String,
    val latestBackupFile: String,
    val noBackupFound: String,
    val createManualBackup: String,
    val manualBackupSuccess: String,
    val clearAutoBackups: String,
    val clearManualBackups: String,
    val backupsCleared: String,
    val manualBackupsCleared: String,
    val openManualBackupVault: String,
    val categoryManagement: String,
    val categoryManagementDescription: String,
    val categoryAndTagManagement: String,
    val backupVault: String,
    val autoBackup: String,
    val manualBackup: String,
    val restore: String,
    val delete: String,
    val deleteBackupSuccess: String,
    val noManualBackups: String,
    val latestAutoBackup: String,
    val latestManualBackup: String,
    val noAutoBackup: String,
    val noManualBackup: String,
    val close: String,
    val enterBackupName: String,
    val backupNamePlaceholder: String,
    val version: String,
    val helpTutorial: String,
    val helpTutorialDescription: String,
    val github: String,
    val githubDescription: String,
    val contactAuthor: String,
    val contactAuthorDescription: String,
    val poweredBy: String,
    val authorName: String,
    val expenseRatio: String,
    val incomeRatio: String,
    val overallRatio: String,
    val thirdPartyBillImport: String,
    val thirdPartyBillImportDescription: String,
    val importWeChatAlipayBill: String,
    val manageImportedBills: String,
    val selected: String,
    val customizeAppExperience: String,
    val darkThemeEnabled: String,
    val lightThemeEnabled: String,
    val currentLanguage: String,
    val currentCurrency: String,
    val settingsInfo: String,
    val settingsInfoDescription: String,
    val restartAppForChanges: String,
    val chinese: String,
    val english: String,
    val defaultCategory: String,
    val addCategory: String,
    val categoryName: String,
    val renameCategory: String,
    val newName: String,
    val deleteCategory: String,
    val deleteCategoryConfirm: String,
    val navigate: String,
    val back: String,
    val billFiles: String
)

val EnStrings = AppStrings(
    home = "Home",
    statistics = "Statistics",
    categoryStatistics = "Category Statistics",
    settings = "Settings",
    dataManagement = "Data Management",
    quickSettings = "Quick Settings",
    customizeExperience = "Customize your experience",
    dataManagementDescription = "Import, export and backup your data",
    generalSettings = "General Settings",
    generalSettingsDescription = "Theme, language and currency preferences",
    about = "About",
    aboutDescription = "Version info and help tutorial",
    totalAssets = "Total Assets",
    totalBalance = "Total Balance",
    thisMonth = "This Month",
    income = "Income",
    expense = "Expense",
    balanceOverall = "Overall",
    startDate = "Start",
    endDate = "End",
    recentTransactions = "Recent Transactions",
    addTransaction = "Add Transaction",
    editTransaction = "Edit Transaction",
    deleteTransaction = "Delete Transaction",
    deleteConfirm = "Are you sure you want to delete this transaction?",
    amount = "Amount",
    date = "Date",
    category = "Category",
    note = "Note",
    save = "Save",
    daily = "Daily",
    weekly = "Weekly",
    monthly = "Monthly",
    yearly = "Yearly",
    custom = "Custom",
    totalIncome = "Total Income",
    totalExpense = "Total Expense",
    categoryRanking = "Category Ranking",
    noTransactions = "No transactions found for this period.",
    selectRange = "Select Range",
    manualDataManagement = "Manual Data Management",
    uploadBackup = "Upload Standard Backup CSV",
    exportAll = "Export All Transactions to CSV",
    darkMode = "Dark Mode",
    language = "Language",
    currencySymbol = "Currency Symbol",
    newCategory = "New Category",
    name = "Name",
    nameEmptyError = "Name cannot be empty",
    nameExistsError = "Category already exists in this type",
    add = "Add",
    cancel = "Cancel",
    ok = "OK",
    change = "Change",
    other = "Other",
    infoLimitation = "Due to API limitations from WeChat and Alipay for personal developers, automatic syncing is disabled. Please upload a standard CSV file exported from this app to restore backups.",
    localBackupVault = "Local Auto Backup Vault",
    enableAutoBackup = "Enable Auto Backup",
    autoBackupDescription = "Automatically save to local sandbox on any add, delete, or modify operation",
    backupRetentionLimit = "Backup Retention Limit",
    backupRetentionDescription = "New backup retention limit",
    backupRetentionUnit = " copies",
    backupThresholdDescription = "Automatically delete oldest backups when threshold is exceeded",
    currentBackupStatus = "Current Backup Status",
    latestBackupFile = "Latest backup file: ",
    noBackupFound = "No available backup file found",
    createManualBackup = "Create Manual Backup Now",
    manualBackupSuccess = "Manual backup created successfully!",
    clearAutoBackups = "Clear Auto Backups",
    clearManualBackups = "Clear Manual Backups",
    backupsCleared = "Auto backup pool has been forcibly cleared",
    manualBackupsCleared = "Manual backup pool has been forcibly cleared",
    openManualBackupVault = "Open Private Manual Backup Vault",
    categoryManagement = "Category Management",
    categoryManagementDescription = "Unified management of income and expense category information",
    categoryAndTagManagement = "Category & Tag Management",
    backupVault = "Backup Vault",
    autoBackup = "Auto",
    manualBackup = "Manual",
    restore = "Restore",
    delete = "Delete",
    deleteBackupSuccess = "Successfully deleted the selected backup",
    noManualBackups = "You haven't created any manual backups yet.",
    latestAutoBackup = "Latest Auto: ",
    latestManualBackup = "Latest Manual: ",
    noAutoBackup = "No auto backup",
    noManualBackup = "No manual backup",
    close = "Close",
    enterBackupName = "Enter a name for this backup:",
    backupNamePlaceholder = "My Backup",
    version = "Version 1.0.0",
    helpTutorial = "Help & Tutorial",
    helpTutorialDescription = "Learn how to use AccountKeeper to manage your finances",
    github = "GitHub",
    githubDescription = "Follow our open source project",
    contactAuthor = "Contact Author",
    contactAuthorDescription = "Feel free to contact us if you have questions or suggestions",
    poweredBy = "Powered by",
    authorName = "Ricky Miao",
    expenseRatio = "Expense Ratio",
    incomeRatio = "Income Ratio",
    overallRatio = "Overall Ratio",
    thirdPartyBillImport = "Third-party Bill Import",
    thirdPartyBillImportDescription = "Support WeChat and Alipay bill CSV file import",
    importWeChatAlipayBill = "Import WeChat/Alipay Bill",
    manageImportedBills = "Manage Imported Bills",
    selected = "selected",
    customizeAppExperience = "Customize your app experience",
    darkThemeEnabled = "Dark theme is enabled",
    lightThemeEnabled = "Light theme is enabled",
    currentLanguage = "Current language",
    currentCurrency = "Current currency",
    settingsInfo = "Settings Info",
    settingsInfoDescription = "Restart the app for language and currency changes to take effect",
    restartAppForChanges = "Restart the app for changes to take effect",
    chinese = "Chinese",
    english = "English",
    defaultCategory = "Default category",
    addCategory = "Add Category",
    categoryName = "Category Name",
    renameCategory = "Rename Category",
    newName = "New Name",
    deleteCategory = "Delete Category",
    deleteCategoryConfirm = "Are you sure you want to delete custom category \"{name}\"? This action cannot be undone.",
    navigate = "Navigate",
    back = "Back",
    billFiles = "Bill Files"
)

val ZhStrings = AppStrings(
    home = "首页",
    statistics = "统计",
    categoryStatistics = "分类统计",
    settings = "设置",
    dataManagement = "数据管理",
    quickSettings = "快速设置",
    customizeExperience = "自定义您的体验",
    dataManagementDescription = "导入、导出和备份数据",
    generalSettings = "个性化设置",
    generalSettingsDescription = "主题、语言和货币偏好",
    about = "关于",
    aboutDescription = "版本信息和帮助教程",
    totalAssets = "总资产",
    totalBalance = "总余额",
    thisMonth = "本月",
    income = "收入",
    expense = "支出",
    balanceOverall = "综合",
    startDate = "开始",
    endDate = "结束",
    recentTransactions = "近期交易",
    addTransaction = "记录交易",
    editTransaction = "修改交易",
    deleteTransaction = "删除交易",
    deleteConfirm = "确定要删除这条交易吗？",
    amount = "金额",
    date = "日期",
    category = "分类",
    note = "备注",
    save = "保存",
    daily = "日",
    weekly = "周",
    monthly = "月",
    yearly = "年",
    custom = "自定义",
    totalIncome = "总收入",
    totalExpense = "总支出",
    categoryRanking = "分类开销排行",
    noTransactions = "该时段内没有交易记录。",
    selectRange = "选择区间",
    manualDataManagement = "本地数据归档",
    uploadBackup = "导入标准 CSV 备份",
    exportAll = "导出全量账本至 CSV",
    darkMode = "深色模式",
    language = "界面语言",
    currencySymbol = "货币符号",
    newCategory = "自定义分类",
    name = "分类名称",
    nameEmptyError = "分类名不能为空",
    nameExistsError = "该分类已经存在",
    add = "添加",
    cancel = "取消",
    ok = "确定",
    change = "修改",
    other = "其他",
    infoLimitation = "因受限于微信与支付宝开放平台对个人开发者的 API 限制，在线直连拉取功能暂不可用。请上传由本软件导出的标准 CSV 历史文件来完成数据合并覆盖。",
    localBackupVault = "本地自动备份安全柜",
    enableAutoBackup = "开启本地自动备份",
    autoBackupDescription = "任何增删改时自动向本地沙盒存入留档",
    backupRetentionLimit = "新备份生成保留上限",
    backupRetentionDescription = "新备份生成保留上限",
    backupRetentionUnit = " 份",
    backupThresholdDescription = "超过此设定阈值时，自动销毁最远历史备份",
    currentBackupStatus = "当前存档状态",
    latestBackupFile = "最新备份文件: ",
    noBackupFound = "尚未发现可用备份文件",
    createManualBackup = "立即创建手动备份",
    manualBackupSuccess = "手动备份创建成功！",
    clearAutoBackups = "清空自动备份",
    clearManualBackups = "清空手动备份",
    backupsCleared = "自动备份池已被强制清空",
    manualBackupsCleared = "手动备份池已被强制清空",
    openManualBackupVault = "打开手动备份私密柜",
    categoryManagement = "分类配置",
    categoryManagementDescription = "统一管理收入与支出的分类信息",
    categoryAndTagManagement = "类别与标签管理",
    backupVault = "备份管理柜",
    autoBackup = "自动",
    manualBackup = "手动",
    restore = "恢复",
    delete = "删除",
    deleteBackupSuccess = "已成功删除选定的存档",
    noManualBackups = "您当前还没有生成任何手动备份。",
    latestAutoBackup = "最新自动: ",
    latestManualBackup = "最新手动: ",
    noAutoBackup = "无自动备份",
    noManualBackup = "无手动备份",
    close = "关闭",
    enterBackupName = "为此备份输入名称：",
    backupNamePlaceholder = "我的备份",
    version = "版本 1.0.0",
    helpTutorial = "帮助教程",
    helpTutorialDescription = "了解如何使用AccountKeeper来管理您的财务",
    github = "GitHub",
    githubDescription = "欢迎关注我们的开源项目",
    contactAuthor = "联系作者",
    contactAuthorDescription = "如有问题或建议，欢迎联系我们",
    poweredBy = "Powered by",
    authorName = "Ricky Miao",
    expenseRatio = "支出比例",
    incomeRatio = "收入比例",
    overallRatio = "综合比例",
    thirdPartyBillImport = "第三方账单导入",
    thirdPartyBillImportDescription = "支持微信和支付宝账单CSV文件导入",
    importWeChatAlipayBill = "导入微信/支付宝账单",
    manageImportedBills = "管理已导入的账单文件",
    selected = "已选择",
    customizeAppExperience = "自定义您的应用体验",
    darkThemeEnabled = "当前使用深色主题",
    lightThemeEnabled = "当前使用浅色主题",
    currentLanguage = "当前语言",
    currentCurrency = "当前货币符号",
    settingsInfo = "设置说明",
    settingsInfoDescription = "更改语言和货币符号后，重启应用即可生效",
    restartAppForChanges = "更改语言和货币符号后，重启应用即可生效",
    chinese = "中文",
    english = "English",
    defaultCategory = "默认分类",
    addCategory = "新增分类",
    categoryName = "分类名称",
    renameCategory = "重命名分类",
    newName = "新名称",
    deleteCategory = "删除分类",
    deleteCategoryConfirm = "确定要删除自定义分类 \"{name}\" 吗？此操作无法撤销。",
    navigate = "导航",
    back = "返回",
    billFiles = "账单文件"
)

val LocalAppStrings = androidx.compose.runtime.compositionLocalOf { EnStrings }